import {
    VerticalBox,
    HorizontalBox,
    LineEdit,
    Button,
    GridBox,
    SpinBox,
    CheckBox,
    Palette,
    ComboBox,
    ListView,
} from "std-widgets.slint";

import { Style } from "style.slint";
import {
    DiffParameter,
    DiffLine,
    LineNumbers,
    FileDiffView,
} from "file_diff_widget.slint";

export { Style, DiffParameter, DiffLine, LineNumbers }

import "../assets/fonts/JetBrainsMonoNL-Thin.ttf";
import "../assets/fonts/JetBrainsMonoNL-ExtraLight.ttf";
import "../assets/fonts/JetBrainsMonoNL-Light.ttf";
import "../assets/fonts/JetBrainsMonoNL-Regular.ttf";
import "../assets/fonts/JetBrainsMonoNL-Medium.ttf";
import "../assets/fonts/JetBrainsMonoNL-Bold.ttf";
import "../assets/fonts/JetBrainsMonoNL-SemiBold.ttf";
import "../assets/fonts/JetBrainsMonoNL-ExtraBold.ttf";

component FormatEditor inherits HorizontalLayout {
    in property <int> current_theme_index;
    in property <[string]> themes;
    callback set_theme(string);

    alignment: start;
    spacing: 5px;

    HorizontalLayout {
        spacing: 5px;
        Text {
            text: "Font size";
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        SpinBox {
            minimum: 6;
            maximum: 40;
            value: Style.font_size / 1px;
            edited(value) => {
                Style.font_size = value * 1px;
            }
        }
    }

    HorizontalLayout {
        spacing: 5px;
        Text {
            text: "Color theme";
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        ComboBox {
            width: 200px;
            current-index: root.current_theme_index;
            model: root.themes;
            selected(current-value) => {
                root.set_theme(current-value)
            }
        }
    }
}

component DiffParameterEditor inherits GridBox {
    in-out property <DiffParameter> parameter;
    callback load_diff();

    spacing: 10px;

    Row {
        Text {
            text: "From Commit:";
            vertical-alignment: center;
        }

        LineEdit {
            text <=> parameter.from;
        }

        Text {
            text: "To Commit:";
            vertical-alignment: center;
        }

        LineEdit {
            text <=> parameter.to;
        }
    }

    Row {
        Text {
            text: "Repository";
            vertical-alignment: center;
        }

        LineEdit {
            text <=> parameter.repository;
        }

        Text {
            text: "File to diff";
            vertical-alignment: center;
        }

        LineEdit {
            text <=> parameter.filename;
        }
    }

    Row {
        Rectangle {
            colspan: 4;

            Button {
                width: 100px;
                text: "Load Diff";
                enabled: !parameter.filename.is-empty && !parameter.from.is-empty && !parameter.to.is-empty && !parameter.repository.is-empty;
                clicked => {
                    load_diff();
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    preferred-width: 1200px;
    preferred-height: 800px;
    title: "Git Diff Viewer";

    in property <[DiffLine]> diff_model;
    in property <[string]> themes;
    in-out property <int> current_theme_index;
    private property <string> line_number_max_digits: "\{diff_model.length}";
    private property <DiffParameter> parameter: {
        from: "",
        to: "",
        repository: "",
        filename: "",
    };

    callback load_diff(DiffParameter);
    callback set_theme(string);

    VerticalBox {
        padding: 10px;
        spacing: 10px;

        DiffParameterEditor {
            parameter <=> root.parameter;
            load_diff => {
                root.load_diff(root.parameter)
            }
        }

        FormatEditor {
            current_theme_index: root.current_theme_index;
            themes: root.themes;
            set_theme(new_theme) => {
                root.set_theme(new_theme)
            }
        }

        FileDiffView {
            diff_model: root.diff_model;
        }
    }
}
